// Department actionsTypes

export const DEPARTMENT_GET_DATA = "DEPARTMENT_GET_DATA";
export const DEPARTMENT_SET_DATA = "DEPARTMENT_SET_DATA";
export const DEPARTMENT_FAIL_DATA = "DEPARTMENT_FAIL_DATA";
export const DELETE_DEPARTMENT_FAIL = "DELETE_DEPARTMENT_FAIL";
export const POST_DEPARTMENT_DATA = "POST_DEPARTMENT_DATA";
export const POST_DEPARTMENT_DATA_START = "POST_DEPARTMENT_DATA_START";
export const POST_DEPARTMENT_DATA_FAIL = "POST_DEPARTMENT_DATA_FAIL";
export const EDIT_DEPARTMENT_ROW_START = "EDIT_DEPARTMENT_ROW_START";

export const FAIL_EDIT_DEPARTMENT = "FAIL_EDIT_DEPARTMENT";
export const CURRENT_USER_EDIT_DEPARTMENT = "CURRENT_USER_EDIT_DEPARTMENT";
export const UPDATE_DEPARTMENT_DATA_START = "UPDATE_DEPARTMENT_DATA_START";

// Form ActionTypes

export const FORM_GET_DATA = "FORM_GET_DATA";
export const FORM_SET_DATA = "FORM_SET_DATA";
export const FORM_FAIL_DATA = "FORM_FAIL_DATA";
export const DELETE_FORM_FAIL = "DELETE_FORM_FAIL";
export const POST_FORM_DATA = "POST_FORM_DATA";
export const POST_FORM_DATA_START = "POST_FORM_DATA_START";
export const POST_FORM_DATA_FAIL = "POST_FORM_DATA_FAIL";
export const EDIT_FORM_ROW_START = "EDIT_FORM_ROW_START";

export const FAIL_EDIT_FORM = "FAIL_EDIT_FORM";
export const CURRENT_USER_EDIT_FORM = "CURRENT_USER_EDIT_FORM";
export const UPDATE_FORM_DATA_START = "UPDATE_FORM_DATA_START";

// Prefix actionTypes

export const PREFIX_GET_DATA = "PREFIX_GET_DATA";
export const PREFIX_SET_DATA = "PREFIX_SET_DATA";
export const PREFIX_FAIL_DATA = "PREFIX_FAIL_DATA";
export const DELETE_PREFIX_FAIL = "DELETE_PREFIX_FAIL";
export const POST_PREFIX_DATA = "POST_PREFIX_DATA";
export const POST_PREFIX_DATA_START = "POST_PREFIX_DATA_START";
export const POST_PREFIX_DATA_FAIL = "POST_PREFIX_DATA_FAIL";
export const EDIT_PREFIX_ROW_START = "EDIT_PREFIX_ROW_START";

export const FAIL_EDIT_PREFIX = "FAIL_EDIT_PREFIX";
export const CURRENT_USER_EDIT_PREFIX = "CURRENT_USER_EDIT_PREFIX";
export const UPDATE_PREFIX_DATA_START = "UPDATE_PREFIX_DATA_START";

// Account Group actionTypes

export const ACCOUNT_GROUP_GET_DATA = "ACCOUNT_GROUP_GET_DATA";
export const ACCOUNT_GROUP_SET_DATA = "ACCOUNT_GROUP_SET_DATA";
export const ACCOUNT_GROUP_FAIL_DATA = "ACCOUNT_GROUP_FAIL_DATA";
export const DELETE_ACCOUNT_GROUP_FAIL = "DELETE_ACCOUNT_GROUP_FAIL";
export const POST_ACCOUNT_GROUP_DATA = "POST_ACCOUNT_GROUP_DATA";
export const POST_ACCOUNT_GROUP_DATA_START = "POST_ACCOUNT_GROUP_DATA_START";
export const POST_ACCOUNT_GROUP_DATA_FAIL = "POST_ACCOUNT_GROUP_DATA_FAIL";
export const EDIT_ACCOUNT_GROUP_ROW_START = "EDIT_ACCOUNT_GROUP_ROW_START";

export const FAIL_EDIT_ACCOUNT_GROUP = "FAIL_EDIT_ACCOUNT_GROUP";
export const CURRENT_USER_EDIT_ACCOUNT_GROUP =
  "CURRENT_USER_EDIT_ACCOUNT_GROUP";
export const UPDATE_ACCOUNT_GROUP_DATA_START =
  "UPDATE_ACCOUNT_GROUP_DATA_START";

// Account Name actionTypes

export const ACCOUNT_NAME_GET_DATA = "ACCOUNT_NAME_GET_DATA";
export const ACCOUNT_NAME_SET_DATA = "ACCOUNT_NAME_SET_DATA";
export const ACCOUNT_NAME_FAIL_DATA = "ACCOUNT_NAME_FAIL_DATA";
export const DELETE_ACCOUNT_NAME_FAIL = "DELETE_ACCOUNT_NAME_FAIL";
export const POST_ACCOUNT_NAME_DATA = "POST_ACCOUNT_NAME_DATA";
export const POST_ACCOUNT_NAME_DATA_START = "POST_ACCOUNT_NAME_DATA_START";
export const POST_ACCOUNT_NAME_DATA_FAIL = "POST_ACCOUNT_NAME_DATA_FAIL";
export const EDIT_ACCOUNT_NAME_ROW_START = "EDIT_ACCOUNT_NAME_ROW_START";

export const FAIL_EDIT_ACCOUNT_NAME = "FAIL_EDIT_ACCOUNT_NAME";

export const UPDATE_ACCOUNT_NAME_DATA_START = "UPDATE_ACCOUNT_NAME_DATA_START";

// Item Group actionTypes

export const ITEM_GROUP_GET_DATA = "ITEM_GROUP_GET_DATA";
export const ITEM_GROUP_SET_DATA = "ITEM_GROUP_SET_DATA";
export const ITEM_GROUP_FAIL_DATA = "ITEM_GROUP_FAIL_DATA";
export const DELETE_ITEM_GROUP_FAIL = "DELETE_ITEM_GROUP_FAIL";
export const POST_ITEM_GROUP_DATA = "POST_ITEM_GROUP_DATA";
export const POST_ITEM_GROUP_DATA_START = "POST_ITEM_GROUP_DATA_START";
export const POST_ITEM_GROUP_DATA_FAIL = "POST_ITEM_GROUP_DATA_FAIL";
export const EDIT_ITEM_GROUP_ROW_START = "EDIT_ITEM_GROUP_ROW_START";

export const FAIL_EDIT_ITEM_GROUP = "FAIL_EDIT_ITEM_GROUP";
export const CURRENT_USER_EDIT_ITEM_GROUP = "CURRENT_USER_EDIT_ITEM_GROUP";
export const UPDATE_ITEM_GROUP_DATA_START = "UPDATE_ITEM_GROUP_DATA_START";

// ITEM Name actionTypes

export const ITEM_NAME_GET_DATA = "ITEM_NAME_GET_DATA";
export const ITEM_NAME_SET_DATA = "ITEM_NAME_SET_DATA";
export const ITEM_NAME_FAIL_DATA = "ITEM_NAME_FAIL_DATA";
export const DELETE_ITEM_NAME_FAIL = "DELETE_ITEM_NAME_FAIL";
export const POST_ITEM_NAME_DATA = "POST_ITEM_NAME_DATA";
export const POST_ITEM_NAME_DATA_START = "POST_ITEM_NAME_DATA_START";
export const POST_ITEM_NAME_DATA_FAIL = "POST_ITEM_NAME_DATA_FAIL";
export const EDIT_ITEM_NAME_ROW_START = "EDIT_ITEM_NAME_ROW_START";

export const FAIL_EDIT_ITEM_NAME = "FAIL_EDIT_ITEM_NAME";

export const UPDATE_ITEM_NAME_DATA_START = "UPDATE_ITEM_NAME_DATA_START";

// ITEM Units actionTypes

export const ITEM_UNITS_GET_DATA = "ITEM_UNITS_GET_DATA";
export const ITEM_UNITS_SET_DATA = "ITEM_UNITS_SET_DATA";
export const ITEM_UNITS_FAIL_DATA = "ITEM_UNITS_FAIL_DATA";
export const DELETE_ITEM_UNITS_FAIL = "DELETE_ITEM_UNITS_FAIL";
export const POST_ITEM_UNITS_DATA = "POST_ITEM_UNITS_DATA";
export const POST_ITEM_UNITS_DATA_START = "POST_ITEM_UNITS_DATA_START";
export const POST_ITEM_UNITS_DATA_FAIL = "POST_ITEM_UNITS_DATA_FAIL";
export const EDIT_ITEM_UNITS_ROW_START = "EDIT_ITEM_UNITS_ROW_START";

export const FAIL_EDIT_ITEM_UNITS = "FAIL_EDIT_ITEM_UNITS";

export const UPDATE_ITEM_UNITS_DATA_START = "UPDATE_ITEM_UNITS_DATA_START";

// UserMaster actionTypes

export const USER_MASTER_GET_DATA = "USER_MASTER_GET_DATA";
export const USER_MASTER_SET_DATA = "USER_MASTER_SET_DATA";
export const USER_MASTER_FAIL_DATA = "USER_MASTER_FAIL_DATA";
export const DELETE_USER_MASTER_FAIL = "DELETE_USER_MASTER_FAIL";
export const POST_USER_MASTER_DATA = "POST_USER_MASTER_DATA";
export const POST_USER_MASTER_DATA_START = "POST_USER_MASTER_DATA_START";
export const POST_USER_MASTER_DATA_FAIL = "POST_USER_MASTER_DATA_FAIL";
export const EDIT_USER_MASTER_ROW_START = "EDIT_USER_MASTER_ROW_START";

export const FAIL_EDIT_USER_MASTER = "FAIL_EDIT_USER_MASTER";
export const CURRENT_USER_EDIT_USER_MASTER = "CURRENT_USER_EDIT_USER_MASTER";
export const UPDATE_USER_MASTER_DATA_START = "UPDATE_USER_MASTER_DATA_START";
